# Generated by Django 5.2 on 2025-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
